CREATE TABLE secrets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    project_uuid UUID NOT NULL,
    environment_uuid UUID NOT NULL,
    secret_key VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(30) NOT NULL,
    created_by UUID NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    UNIQUE(project_uuid, environment_uuid, secret_key)
);

CREATE TABLE secret_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    secret_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    encrypted_value TEXT NOT NULL,
    encryption_key_id VARCHAR(255) NOT NULL,
    created_by UUID NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_secret_versions_secret FOREIGN KEY (secret_id) REFERENCES secrets(id),
    UNIQUE(secret_id, version_number)
);

CREATE INDEX idx_secrets_project_env ON secrets(project_uuid, environment_uuid);
CREATE INDEX idx_secret_versions_secret ON secret_versions(secret_id);
